version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    container_name: tracker_db
    environment:
      - POSTGRES_USER=tracker_user
      - POSTGRES_PASSWORD=tracker_pass
      - POSTGRES_DB=tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
